# Generated by Django 6.0.5 on 2026-05-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["-created_time"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_time"]},
        ),
    ]
