# Generated by Django 6.0.5 on 2026-05-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_commentary_options_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["-created_time"],
                "verbose_name": "commentary",
                "verbose_name_plural": "commentaries",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_time"],
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
